apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-pzu6
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0068-tenant/ci10t-786-0068-app/devfile-sample-pzu6@sha256:d000dfd98fd6fe735eb4c33e19ca0143e330917208422bbc341c4ea097005bac
        name: my-nodejs
        resources: {}
status: {}
